// <auto-generated />
using System;
using DevSilenceKeeperBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevSilenceKeeperBot.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20200706184603_DbInit")]
    partial class DbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevSilenceKeeperBot.Data.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("DevSilenceKeeperBot.Data.Entities.ForbiddenChatWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ForbiddenChatWords");
                });

            modelBuilder.Entity("DevSilenceKeeperBot.Data.Entities.ManyToMany.ChatToPromotedMember", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<int>("PromotedMemberId")
                        .HasColumnType("int");

                    b.HasKey("ChatId", "PromotedMemberId");

                    b.HasIndex("PromotedMemberId");

                    b.ToTable("ChatToPromotedMembers");
                });

            modelBuilder.Entity("DevSilenceKeeperBot.Data.Entities.PromotedChatMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("PromotedMembers");
                });

            modelBuilder.Entity("DevSilenceKeeperBot.Data.Entities.ForbiddenChatWord", b =>
                {
                    b.HasOne("DevSilenceKeeperBot.Data.Entities.Chat", "Chat")
                        .WithMany("ForbiddenWords")
                        .HasForeignKey("ChatId");
                });

            modelBuilder.Entity("DevSilenceKeeperBot.Data.Entities.ManyToMany.ChatToPromotedMember", b =>
                {
                    b.HasOne("DevSilenceKeeperBot.Data.Entities.Chat", "Chat")
                        .WithMany("PromotedMembers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevSilenceKeeperBot.Data.Entities.PromotedChatMember", "PromotedChatMember")
                        .WithMany("Chats")
                        .HasForeignKey("PromotedMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
